<?php

/**
 * @file
 * The main file of the feeds_excel module.
 */

/**
 * Implements hook_feeds_plugins().
 */
function feeds_excel_feeds_plugins() {
  $info = array();
  $info['FeedsExcelParser'] = array(
    'name'        => 'Excel parser',
    'description' => 'Parse data in xls, xlsx formats.',
    'handler'     => array(
      'parent' => 'FeedsParser',
      'class'  => 'FeedsExcelParser',
      'file'   => 'FeedsExcelParser.inc',
      'path'   => drupal_get_path('module', 'feeds_excel'),
    ),
  );
  return $info;
}

/**
 * Implements hook_libraries_info().
 */
function feeds_excel_libraries_info() {
  $libraries = array();
  $libraries['PHPExcel'] = array(
    'name'              => 'PHPExcel',
    'vendor url'        => 'https://github.com/PHPOffice/PHPExcel',
    'download url'      => 'https://github.com/PHPOffice/PHPExcel/archive/1.8.zip',
    'path'              => 'Classes',
    'files'             => array('php' => array('PHPExcel.php', 'PHPExcel/IOFactory.php')),
    'version arguments' => array(
      'file'    => 'install.txt',
      'pattern' => '@version\s+([0-9a-zA-Z\.-]+)@',
      'lines'   => 22,
    ),
  );
  return $libraries;
}
